name: "\U0001F41B Bug report"
description: Submit a bug report to help us improve qianfan.
labels: ["Bug"]
body:
  - type: markdown
    attributes:
      value: >
        Thank you for taking the time to file a bug report! Before you do so,
        please take a look at existing open issues and make sure that your
        issue is not already documented. If it isn't, please provide us with a
        clear and concise description of what the bug is.
  - type: textarea
    id: system-info
    attributes:
      label: System Info
      description: Please share your system info with us.
      placeholder: |
        **qianfan version**
        - qianfan version: 

        **System Version**
        - Python Version: 
        - Operating System: 
    validations:
      required: true

  - type: textarea
    id: reproduction
    validations:
      required: true
    attributes:
      label: Reproduction
      description: |
        Please provide a code sample to reproduce this bug.
      placeholder: |
        1. Install qianfan '....'
        2. Make API call '....'
        3. See error

        **Expected behavior**
        A clear and concise description of what you expected to happen.

        **Additional context**
        Add any other context about the problem here.
