name: "\U0001F41B Bug report"
about: Submit a bug report to help us improve qianfan.
labels: ["01 Bug"]
assignees: ''

**Describe the bug**
Thank you for taking the time to file a bug report! Before you do so, please take a look at existing open issues and make sure that your issue is not already documented. If it isn't, please provide us with a clear and concise description of what the bug is.

**qianfan version**
- qianfan version: 

**System Version**
- Python Version: 
- Operating System: 

**Minimal Reproducible Example**
Steps to reproduce the behavior:
1. Install qianfan '....'
2. Make API call '....'
3. See error

Please provide a code snippet that documents how your bug can be reproduced.
```
import qianfan
...
```

**Expected behavior**
A clear and concise description of what you expected to happen.

**Additional context**
Add any other context about the problem here.