name: Custom Issue
description: Raise an issue other
title: "Issue: <Title for breif intro about this issue. 'Issue: ' prefix>"
labels: ["02 Custom"]

body:
  - type: textarea
    attributes:
      label: "Issue you'd like to raise."
      description: >
        Please describe the issue you'd like to raise as clearly as possible.
        Make sure to include any relevant links or references.

  - type: textarea
    attributes:
      label: "Suggestion:"
      description: >
        Please outline a suggestion to improve the issue here.
